# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/Compiler_Assginment

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/Compiler_Assginment

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/Compiler_Assginment/CMakeFiles /root/Compiler_Assginment/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/Compiler_Assginment/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Compiler

# Build rule for target.
Compiler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Compiler
.PHONY : Compiler

# fast build rule for target.
Compiler/fast:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/build
.PHONY : Compiler/fast

common/compile_errors.o: common/compile_errors.cpp.o

.PHONY : common/compile_errors.o

# target to build an object file
common/compile_errors.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/common/compile_errors.cpp.o
.PHONY : common/compile_errors.cpp.o

common/compile_errors.i: common/compile_errors.cpp.i

.PHONY : common/compile_errors.i

# target to preprocess a source file
common/compile_errors.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/common/compile_errors.cpp.i
.PHONY : common/compile_errors.cpp.i

common/compile_errors.s: common/compile_errors.cpp.s

.PHONY : common/compile_errors.s

# target to generate assembly for a file
common/compile_errors.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/common/compile_errors.cpp.s
.PHONY : common/compile_errors.cpp.s

common/utils.o: common/utils.cpp.o

.PHONY : common/utils.o

# target to build an object file
common/utils.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/common/utils.cpp.o
.PHONY : common/utils.cpp.o

common/utils.i: common/utils.cpp.i

.PHONY : common/utils.i

# target to preprocess a source file
common/utils.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/common/utils.cpp.i
.PHONY : common/utils.cpp.i

common/utils.s: common/utils.cpp.s

.PHONY : common/utils.s

# target to generate assembly for a file
common/utils.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/common/utils.cpp.s
.PHONY : common/utils.cpp.s

file_reader/file_reader.o: file_reader/file_reader.cpp.o

.PHONY : file_reader/file_reader.o

# target to build an object file
file_reader/file_reader.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/file_reader/file_reader.cpp.o
.PHONY : file_reader/file_reader.cpp.o

file_reader/file_reader.i: file_reader/file_reader.cpp.i

.PHONY : file_reader/file_reader.i

# target to preprocess a source file
file_reader/file_reader.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/file_reader/file_reader.cpp.i
.PHONY : file_reader/file_reader.cpp.i

file_reader/file_reader.s: file_reader/file_reader.cpp.s

.PHONY : file_reader/file_reader.s

# target to generate assembly for a file
file_reader/file_reader.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/file_reader/file_reader.cpp.s
.PHONY : file_reader/file_reader.cpp.s

lexer/dfa.o: lexer/dfa.cpp.o

.PHONY : lexer/dfa.o

# target to build an object file
lexer/dfa.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/lexer/dfa.cpp.o
.PHONY : lexer/dfa.cpp.o

lexer/dfa.i: lexer/dfa.cpp.i

.PHONY : lexer/dfa.i

# target to preprocess a source file
lexer/dfa.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/lexer/dfa.cpp.i
.PHONY : lexer/dfa.cpp.i

lexer/dfa.s: lexer/dfa.cpp.s

.PHONY : lexer/dfa.s

# target to generate assembly for a file
lexer/dfa.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/lexer/dfa.cpp.s
.PHONY : lexer/dfa.cpp.s

lexer/lex_item.o: lexer/lex_item.cpp.o

.PHONY : lexer/lex_item.o

# target to build an object file
lexer/lex_item.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/lexer/lex_item.cpp.o
.PHONY : lexer/lex_item.cpp.o

lexer/lex_item.i: lexer/lex_item.cpp.i

.PHONY : lexer/lex_item.i

# target to preprocess a source file
lexer/lex_item.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/lexer/lex_item.cpp.i
.PHONY : lexer/lex_item.cpp.i

lexer/lex_item.s: lexer/lex_item.cpp.s

.PHONY : lexer/lex_item.s

# target to generate assembly for a file
lexer/lex_item.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/lexer/lex_item.cpp.s
.PHONY : lexer/lex_item.cpp.s

lexer/lex_table.o: lexer/lex_table.cpp.o

.PHONY : lexer/lex_table.o

# target to build an object file
lexer/lex_table.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/lexer/lex_table.cpp.o
.PHONY : lexer/lex_table.cpp.o

lexer/lex_table.i: lexer/lex_table.cpp.i

.PHONY : lexer/lex_table.i

# target to preprocess a source file
lexer/lex_table.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/lexer/lex_table.cpp.i
.PHONY : lexer/lex_table.cpp.i

lexer/lex_table.s: lexer/lex_table.cpp.s

.PHONY : lexer/lex_table.s

# target to generate assembly for a file
lexer/lex_table.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/lexer/lex_table.cpp.s
.PHONY : lexer/lex_table.cpp.s

lexer/lexer.o: lexer/lexer.cpp.o

.PHONY : lexer/lexer.o

# target to build an object file
lexer/lexer.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/lexer/lexer.cpp.o
.PHONY : lexer/lexer.cpp.o

lexer/lexer.i: lexer/lexer.cpp.i

.PHONY : lexer/lexer.i

# target to preprocess a source file
lexer/lexer.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/lexer/lexer.cpp.i
.PHONY : lexer/lexer.cpp.i

lexer/lexer.s: lexer/lexer.cpp.s

.PHONY : lexer/lexer.s

# target to generate assembly for a file
lexer/lexer.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/lexer/lexer.cpp.s
.PHONY : lexer/lexer.cpp.s

lexer/vocab.o: lexer/vocab.cpp.o

.PHONY : lexer/vocab.o

# target to build an object file
lexer/vocab.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/lexer/vocab.cpp.o
.PHONY : lexer/vocab.cpp.o

lexer/vocab.i: lexer/vocab.cpp.i

.PHONY : lexer/vocab.i

# target to preprocess a source file
lexer/vocab.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/lexer/vocab.cpp.i
.PHONY : lexer/vocab.cpp.i

lexer/vocab.s: lexer/vocab.cpp.s

.PHONY : lexer/vocab.s

# target to generate assembly for a file
lexer/vocab.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/lexer/vocab.cpp.s
.PHONY : lexer/vocab.cpp.s

machine/machine.o: machine/machine.cpp.o

.PHONY : machine/machine.o

# target to build an object file
machine/machine.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/machine/machine.cpp.o
.PHONY : machine/machine.cpp.o

machine/machine.i: machine/machine.cpp.i

.PHONY : machine/machine.i

# target to preprocess a source file
machine/machine.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/machine/machine.cpp.i
.PHONY : machine/machine.cpp.i

machine/machine.s: machine/machine.cpp.s

.PHONY : machine/machine.s

# target to generate assembly for a file
machine/machine.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/machine/machine.cpp.s
.PHONY : machine/machine.cpp.s

machine/stack.o: machine/stack.cpp.o

.PHONY : machine/stack.o

# target to build an object file
machine/stack.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/machine/stack.cpp.o
.PHONY : machine/stack.cpp.o

machine/stack.i: machine/stack.cpp.i

.PHONY : machine/stack.i

# target to preprocess a source file
machine/stack.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/machine/stack.cpp.i
.PHONY : machine/stack.cpp.i

machine/stack.s: machine/stack.cpp.s

.PHONY : machine/stack.s

# target to generate assembly for a file
machine/stack.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/machine/stack.cpp.s
.PHONY : machine/stack.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/main.cpp.s
.PHONY : main.cpp.s

parser/astree.o: parser/astree.cpp.o

.PHONY : parser/astree.o

# target to build an object file
parser/astree.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/parser/astree.cpp.o
.PHONY : parser/astree.cpp.o

parser/astree.i: parser/astree.cpp.i

.PHONY : parser/astree.i

# target to preprocess a source file
parser/astree.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/parser/astree.cpp.i
.PHONY : parser/astree.cpp.i

parser/astree.s: parser/astree.cpp.s

.PHONY : parser/astree.s

# target to generate assembly for a file
parser/astree.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/parser/astree.cpp.s
.PHONY : parser/astree.cpp.s

parser/ins_table.o: parser/ins_table.cpp.o

.PHONY : parser/ins_table.o

# target to build an object file
parser/ins_table.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/parser/ins_table.cpp.o
.PHONY : parser/ins_table.cpp.o

parser/ins_table.i: parser/ins_table.cpp.i

.PHONY : parser/ins_table.i

# target to preprocess a source file
parser/ins_table.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/parser/ins_table.cpp.i
.PHONY : parser/ins_table.cpp.i

parser/ins_table.s: parser/ins_table.cpp.s

.PHONY : parser/ins_table.s

# target to generate assembly for a file
parser/ins_table.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/parser/ins_table.cpp.s
.PHONY : parser/ins_table.cpp.s

parser/instructions.o: parser/instructions.cpp.o

.PHONY : parser/instructions.o

# target to build an object file
parser/instructions.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/parser/instructions.cpp.o
.PHONY : parser/instructions.cpp.o

parser/instructions.i: parser/instructions.cpp.i

.PHONY : parser/instructions.i

# target to preprocess a source file
parser/instructions.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/parser/instructions.cpp.i
.PHONY : parser/instructions.cpp.i

parser/instructions.s: parser/instructions.cpp.s

.PHONY : parser/instructions.s

# target to generate assembly for a file
parser/instructions.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/parser/instructions.cpp.s
.PHONY : parser/instructions.cpp.s

parser/parser.o: parser/parser.cpp.o

.PHONY : parser/parser.o

# target to build an object file
parser/parser.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/parser/parser.cpp.o
.PHONY : parser/parser.cpp.o

parser/parser.i: parser/parser.cpp.i

.PHONY : parser/parser.i

# target to preprocess a source file
parser/parser.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/parser/parser.cpp.i
.PHONY : parser/parser.cpp.i

parser/parser.s: parser/parser.cpp.s

.PHONY : parser/parser.s

# target to generate assembly for a file
parser/parser.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/parser/parser.cpp.s
.PHONY : parser/parser.cpp.s

parser/sym_table.o: parser/sym_table.cpp.o

.PHONY : parser/sym_table.o

# target to build an object file
parser/sym_table.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/parser/sym_table.cpp.o
.PHONY : parser/sym_table.cpp.o

parser/sym_table.i: parser/sym_table.cpp.i

.PHONY : parser/sym_table.i

# target to preprocess a source file
parser/sym_table.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/parser/sym_table.cpp.i
.PHONY : parser/sym_table.cpp.i

parser/sym_table.s: parser/sym_table.cpp.s

.PHONY : parser/sym_table.s

# target to generate assembly for a file
parser/sym_table.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/parser/sym_table.cpp.s
.PHONY : parser/sym_table.cpp.s

parser/symbol.o: parser/symbol.cpp.o

.PHONY : parser/symbol.o

# target to build an object file
parser/symbol.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/parser/symbol.cpp.o
.PHONY : parser/symbol.cpp.o

parser/symbol.i: parser/symbol.cpp.i

.PHONY : parser/symbol.i

# target to preprocess a source file
parser/symbol.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/parser/symbol.cpp.i
.PHONY : parser/symbol.cpp.i

parser/symbol.s: parser/symbol.cpp.s

.PHONY : parser/symbol.s

# target to generate assembly for a file
parser/symbol.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/parser/symbol.cpp.s
.PHONY : parser/symbol.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Compiler"
	@echo "... edit_cache"
	@echo "... common/compile_errors.o"
	@echo "... common/compile_errors.i"
	@echo "... common/compile_errors.s"
	@echo "... common/utils.o"
	@echo "... common/utils.i"
	@echo "... common/utils.s"
	@echo "... file_reader/file_reader.o"
	@echo "... file_reader/file_reader.i"
	@echo "... file_reader/file_reader.s"
	@echo "... lexer/dfa.o"
	@echo "... lexer/dfa.i"
	@echo "... lexer/dfa.s"
	@echo "... lexer/lex_item.o"
	@echo "... lexer/lex_item.i"
	@echo "... lexer/lex_item.s"
	@echo "... lexer/lex_table.o"
	@echo "... lexer/lex_table.i"
	@echo "... lexer/lex_table.s"
	@echo "... lexer/lexer.o"
	@echo "... lexer/lexer.i"
	@echo "... lexer/lexer.s"
	@echo "... lexer/vocab.o"
	@echo "... lexer/vocab.i"
	@echo "... lexer/vocab.s"
	@echo "... machine/machine.o"
	@echo "... machine/machine.i"
	@echo "... machine/machine.s"
	@echo "... machine/stack.o"
	@echo "... machine/stack.i"
	@echo "... machine/stack.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parser/astree.o"
	@echo "... parser/astree.i"
	@echo "... parser/astree.s"
	@echo "... parser/ins_table.o"
	@echo "... parser/ins_table.i"
	@echo "... parser/ins_table.s"
	@echo "... parser/instructions.o"
	@echo "... parser/instructions.i"
	@echo "... parser/instructions.s"
	@echo "... parser/parser.o"
	@echo "... parser/parser.i"
	@echo "... parser/parser.s"
	@echo "... parser/sym_table.o"
	@echo "... parser/sym_table.i"
	@echo "... parser/sym_table.s"
	@echo "... parser/symbol.o"
	@echo "... parser/symbol.i"
	@echo "... parser/symbol.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

