/*
 * @Author: Gao Dechen
 * @LastEditors: Gao Dechen
 * @Description: Operator Table Generated by Parser
 * @LastEditTime: 2020-05-12 10:19:58
 * @Date: 2020-04-25 11:40:45
 */

#include "../parser/ins_table.h"

InsTable::InsTable()
{
    m_pc = 1;
}

int InsTable::AddPC()
{
    return ++m_pc;
}

int InsTable::DecPC()
{
    return --m_pc;
}

int InsTable::GetPC()
{
    return m_pc;
}

void InsTable::Generate(InsCode opt, int level, int offset)
{
    m_codes[m_pc++] = Instruction(opt, level, offset);
}

Instruction& InsTable::operator [] (const int &idx)
{
    return m_codes[idx];
}

std::ostream &operator<<(std::ostream &out, InsTable &obj)
{
    for (int i = 1; i < obj.m_pc; i++)
    {
        out << obj.m_codes[i];
    }
    return out;
}