/*
 * @Author: Gao Dechen
 * @LastEditors: Gao Dechen
 * @Description: Operator Table Generated by Parser
 * @LastEditTime: 2020-05-02 10:42:49
 * @Date: 2020-04-25 11:40:06
 */

#define INC_INS_TABLE

#include <string>
#include <iostream>

#include "../parser/instructions.h"

class InsTable
{
private:
    static const int TABLE_SIZE = 1000;
    Instruction m_codes[TABLE_SIZE];
    int m_pc;

public:
    InsTable();
    int AddPC();
    int DecPC();
    int GetPC();
    void Generate(InsCode opt, int level = 0, int offset = 0);
    Instruction& operator [] (const int &idx);
    friend std::ostream &operator<<(std::ostream &out, InsTable &obj);
};