/*
 * @Author: Gao Dechen
 * @LastEditors: Gao Dechen
 * @Description: Operator Table Generated by Parser
 * @LastEditTime: 2020-04-25 23:56:29
 * @Date: 2020-04-25 11:40:45
 */

#include "../parser/opt_table.h"

OptTable::OptTable()
{
    m_pc = 1;
}

int OptTable::AddPC()
{
    return ++m_pc;
}

int OptTable::DecPC()
{
    return --m_pc;
}

int OptTable::GetPC()
{
    return m_pc;
}

void OptTable::Generate(InsCode opt, int level = 0, int offset = 0)
{
    m_codes[m_pc++] = Instruction(opt, level, offset);
}

Instruction& OptTable::operator [] (const int &idx)
{
    return m_codes[idx];
}