/*
 * @Author: Gao Dechen
 * @LastEditors: Gao Dechen
 * @Description: Operator Table Generated by Parser
 * @LastEditTime: 2020-04-25 23:56:45
 * @Date: 2020-04-25 11:40:06
 */

#define INC_OPT_TABLE

#include <string>

#include "../parser/instructions.h"

class OptTable
{
private:
    static const int TABLE_SIZE = 1000;
    Instruction m_codes[TABLE_SIZE];
    int m_pc;

public:
    OptTable();
    int AddPC();
    int DecPC();
    int GetPC();
    void Generate(InsCode opt, int level = 0, int offset = 0);
    Instruction& operator [] (const int &idx);
};